### ISSUE TITLE
Output file names

### ISSUE THREAD

**Issue by agitter** [Murali-group/PathLinker#4]
I noticed that PathLinker uses a mixture of `_` and `-` as delimiters in file names and that the [default file name](https://github.com/Murali-group/PathLinker/blob/38cb4e607b665720f27cb280c1f62d88ef9fd094/run.py#L174) when running with PageRank preprocessing contains `_-` together.  A small change, such as making the [default `output` parameter](https://github.com/Murali-group/PathLinker/blob/38cb4e607b665720f27cb280c1f62d88ef9fd094/run.py#L32) `out` instead of `out_` and adding the delimiter separately, might make the file names slightly more readable.

This is a very low priority suggestion because it doesn't impact the results.  Everything else has been well-documented and easy to use.

**Comment by tmmurali** [comment]
@agitter Thanks for the suggestion. Making the file names consistent is important. We will get this fixed soon.

**Comment by jlaw9** [comment]
I agree. I replaced `_` file delimiters with `-` and changed the default output parameter to `out` as you suggested @agitter  5a812db2b777759baf8b236daa9eec13e65ea9cf

Thanks!

**Comment by agitter** [comment]
Thanks @jlaw9
